# Generated by Django 4.1.4 on 2023-10-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
