# Generated by Django 4.1.4 on 2023-10-18 09:41

from django.db import migrations, models
import onlineidentity.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_studentprofile_course_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.IntegerField(default=onlineidentity.app.models.create_new_ref_number),
        ),
    ]
