# Generated by Django 4.1.4 on 2023-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksborrow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booksborrow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='booksborrow',
            unique_together={('book', 'student_id', 'active')},
        ),
    ]
